### ISSUE TITLE
[FEATURE]: a feature to search across files in the folder

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#100]
so far, linebyline can search a specific term in the MD file.
But I expect it can search a specific term in all MD file in a folder.

**Comment by halodong** [comment]
The global search function will be completed in a later version, but it may take a while, because there are many functions with higher priority at present, I will notify you when it is completed, thank you

**Comment by yu2chuan** [comment]
it's great. this is an important step.

**Comment by halodong** [comment]
Thank you for your attention. This feature will be released in a few days, it is not very stable yet.

**Comment by yu2chuan** [comment]
It's OK. I love to test it.

**Comment by halodong** [comment]
Thank you for your support, it has been released
