### ISSUE TITLE
[BUG]: a bug is this seems no way to create a new md file

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#102]
**Describe the bug**
There is no way to create a new md file

**Expected behavior**
There should be a way to create a new md file.

**Comment by halodong** [comment]
Thank you for your attention and advice to linebyline

Create new file function has not been developed yet, and it is expected to be added in a small version after 0.1.0, because the current plan for 0.1.0 is to complete some key editor-related content first

**Comment by yu2chuan** [comment]
on verion 0.1.3, I added a file, named 333.  input some words and control+S. But the file 333.md didn't appear in the file list. I switched to anothe fold and opened this folder again. I still couldn't find the file, 333.md. It disappeared.
