### ISSUE TITLE
[FEATURE]: a feature - outline

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#103]
**Is your feature request related to a problem? Please describe.**
we need a way to see the outline easily.

**Describe the solution you'd like**
So far, Marktext provide a good way. But I expect linebyline can create an even better one.

**Comment by halodong** [comment]
Thank you for your attention and advice to linebyline

The outline is already under planning and is expected to be completed in version 0.1.0-alpha. I will remind you when it is completed

**Comment by halodong** [comment]
#122

**Comment by halodong** [comment]
The outline I understand is a mark mark like `*` ,`**`, `~~`, which will be displayed and automatically hidden when you edit to the corresponding node.

But seeing you have a question, it should be my misunderstanding. Can you describe it in more detail?

**Comment by yu2chuan** [comment]
This is the UI of Mark Text. You can take it as a reference. 
https://drive.google.com/uc?id=1e6W1iZMAnTQ6J5oUukGMX527HlCtHNn8

The outline is like a bookmark, index. When the contents is long, users can quickly find the topic in the outline. 
If you are OK to add this, it can add a icon like H under the ChatGPT.

**Comment by halodong** [comment]
Okay, because I usually call it 'table of content', I didn't understand this meaning. This feature should be added in a later version
