### ISSUE TITLE
[FEATURE]: a feature to support html such as <ruby>  <rt>  </rt> </ruby>

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#114]
**Is your feature request related to a problem? Please describe.**
support html such as \<ruby>  \<rt>  \</rt> \</ruby>

**Describe the solution you'd like**
support html such as <ruby>閉<rt>し</rt></ruby>まる

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by halodong** [comment]
This feature will be supported, but due to the large amount of work required, it will be completed at a certain time in the future, rather than in the near future.

**Comment by halodong** [comment]
refer #262
