### ISSUE TITLE
[FEATURE]: a feature to jump to the same line in dual mode while editing

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#115]
**Is your feature request related to a problem? Please describe.**
when I scroll down the left panel, the right panel doesn't move to the same line.
The software may provide an option that users can move to the same line in the dual mode.

**Describe the solution you'd like**
jump to the same line in dual mode while editing

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by halodong** [comment]
This is expected to be completed on 0.1.0.

**Comment by halodong** [comment]
fix with bfbeeaa
