### ISSUE TITLE
[FEATURE]: a feature to support <iframe src="https://drive.google.com/file" width="640" height="480" allow="autoplay"></iframe>

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#128]
**Is your feature request related to a problem? Please describe.**
Is it possible to embed youtube videos or videos on the Google drive via <iframe></iframe>

**Describe the solution you'd like**
support <iframe></iframe> to embed video or podcast or radio on the internet.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by halodong** [comment]
In the markdown editor, this seems not a common requirement and should not be planned in the short term. If there is further feedback from other users, I will consider increasing its priority. thank you

**Comment by yu2chuan** [comment]
Understood. Thanks for the feedback.

**Comment by yu2chuan** [comment]
I  can't wait.

**Comment by halodong** [comment]
Sorry for the long wait. It will be released this Friday and there is still one area that needs to be refactored
