### ISSUE TITLE
[BUG]: a bug '---'

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#130]
**Describe the bug**
The linebyline 0.06 seems to ignore all contents after '---'

**To Reproduce**
1. create a md file with the following
AAAA
\---
BBBB
\---
CCCC
2. Then the editor can show AAAA but ignore everything after '---'

**Expected behavior**
none

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: WIN10
 - Version 0.0.6

**Additional context**
none

**Comment by halodong** [comment]
The reason for not supporting the Horizontal Rule will be fixed tonight. Thank you for your feedback
