### ISSUE TITLE
[FEATURE]: a feature to use physical key instead of clicking SUBMIT in ChatGPT

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#161]
**Is your feature request related to a problem? Please describe.**
After inputting a question in ChatGPT, people should prefer to use ENTER or key combination instead of clicking SUBMIT by mouse.

**Describe the solution you'd like**
Using physical key such as ENTER, Ctrl+ENTER, Alt+ENTER, Shift+ENTER to submit the questions to ChatGPT.

**Describe alternatives you've considered**
users can define their own combination key.

**Additional context**
none.

**Comment by halodong** [comment]
`Enter` trigger will be added in the latest version, and custom shortcut keys will be uniformly supported in the future.
