### ISSUE TITLE
[FEATURE]: a feature to load the latest edited file or folder when the program starts

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#163]
**Is your feature request related to a problem? Please describe.**
When the program starts, I need to select the fold and file every time.

**Describe the solution you'd like**
When the program starts, the program can load the latest edited files or folder.

**Describe alternatives you've considered**
add this option in the settings

**Additional context**
none

**Comment by halodong** [comment]
Good Idea! We will complete it in the latest version

**Comment by yu2chuan** [comment]
Wait for the new release.

**Comment by halodong** [comment]
Currently, a bug has been encountered in the production environment, and it will be released once resolved
