### ISSUE TITLE
[BUG]: a bug is a cursor can't be found when the md file is empty.

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#166]
**Describe the bug**
When the md file is empty, user cannot find the cursor in Wysiwyg mode

**To Reproduce**
1. Open any md file.
2. clean data by Ctrl+A, delete, Crtl+S. In this step, I changed the file to be no content.
3. click the editor area. there is no cursor in Wysiwyg mode.
4. paste contents, Ctrl+V, doesn't work either.

**Expected behavior**
Even the file is empty, there should be a cursor there.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.0.8

**Additional context**
The short term solution is to go to dual mode. add some content in the empty file. Then users can see the cursor again in Wysiwyg.

**Comment by halodong** [comment]
The editing area is not fully occupied. You can try clicking on the top to regain focus,
Will optimize it here through placeholder

**Comment by yu2chuan** [comment]
The cursor appears when I click the area where the first line could be. 
You may consider if this could be a problem in the future if the program can create a new md file, which should be empty. And then users will be difficult to find where the cursor is.

**Comment by halodong** [comment]
I strongly agree, In addition to the placeholder, it will further adjust and expand the click area to obtain the focus.
