### ISSUE TITLE
[BUG]: a bug about open recent folder

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#172]
**Describe the bug**
After picking one from the 'open recent folder list', the recent folder list doesn't close automatically. if users have a long file list, users have to first close the 'open recent folder list' and then can access the md file.

**To Reproduce**
1. create a folder 'AAA' with tons of md files.
2. open several folders, many path will appear in the recent folder list.
3. Now, intentionally choose folder AAA from the 'open recent folder list'
4. if several path in the recent folder list, it will be large enough to block people choosing files in the folder AAA.

**Expected behavior**
After picking one path in the open recent folder list, the list can close on its own. And users should have a way to clear some or all paths in the open recent folder, which they don't need anymore.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.0.8

**Additional context**
And users should have a way to clear some or all paths in the open recent folder

**Comment by halodong** [comment]
Thank you for your feedback, here will be optimize in next version.
