### ISSUE TITLE
[BUG]: a bug - the program crashes when clicking not supporting file format

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#175]
**Describe the bug**
the program crashes when clicking not supporting file format

**To Reproduce**
1. open a folder which includes various formats such as jpg, ppt, doc ,and md.
2. the program will crash when accidently clicking not supporting file format.

**Expected behavior**
only show supporting format such as txt, md or csv in the open folder.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.0.8

**Additional context**
none

**Comment by halodong** [comment]
Thank you for your feedback, Here filtering should be done based on the file format.
