### ISSUE TITLE
[BUG]: a bug about font color of code section in the dark theme

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#184]
**Describe the bug**
Font color of code section in the dark theme isn't easy to read.

**To Reproduce**
1. add a code section \```css and end with ```
2. input some code in the section
3. switch to dark theme
4. code isn't easy to read in the dark theme.

**Expected behavior**
give code sections a gray or a contrasting color as background in the dark theme Or you may have the other better ideas. The purpose is to make the code section can be read easily.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.1.0

**Additional context**
none

**Comment by halodong** [comment]
Thank you for your feedback, we will optimize this.

**Comment by halodong** [comment]
0eb7467

**Comment by yu2chuan** [comment]
so good.
