### ISSUE TITLE
[FEATURE]: a feature to auto save and changes will be lost

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#186]
**Is your feature request related to a problem? Please describe.**
If users close the program, the changes will be lost.

**Describe the solution you'd like**
1. add option auto save every 1/5/10 minute. Or the program can do this silently.
2. when closing the program, users will be reminded changes will be lost with 'save' button and 'ignore and exit' button.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by halodong** [comment]
Nice feature, we will support it in recent versions.

**Comment by yu2chuan** [comment]
on 0.2.2, I just found ctrl+s doesn't work on Source code mode. You may check it has been fixed.
If users stay at source code, presee ctrl+s, and then close the program. The change will be lost.

**Comment by halodong** [comment]
This only happens on windowsOS, it will be fixed in the next version
