### ISSUE TITLE
[BUG]: a bug for incorrectly creating a line break in the table

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#189]
**Describe the bug**
Use shift+enter to create a line break in the table and save the file. After open the md file again, the contents after the line break have been move to the next row.

**To Reproduce**
1. Open a new table
2. randomly input some words in the top row.
3. input 11112222 in the 2nd row. And then move cursor between1111 and 2222. 
4. press shift+enter, it seems to successfully create a line break. 2222 is under 1111,  they are still in the same field. save this md file.
5. open the file again. 2222 has moved to next row.

**Expected behavior**
any way to create a line break in the table. Supporting \<br/> is possible or any better way.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.1.0

**Additional context**
The UI of linebyline is neat and nice to me. That's why I tried a lot. I expect it can be a better tool and it can still remain the small size.

**Comment by halodong** [comment]
We will fix this bug as soon as possible.

**Comment by yu2chuan** [comment]
is it possible to make <br/> work in the table?

**Comment by halodong** [comment]
use `shift + enter` to wrap, will insert `<br />`.

Currently, when opening such a file, there may be '<br/><br/>' but no line breaks. This will be optimized in the next version, which was originally intended to be optimized after supporting HTML.

**Comment by yu2chuan** [comment]
Do you mean linebyline will support something like \<mark>\</mark> or \<u>\</u> or \<ruby>\<rt>\</rt>\</ruby>?

By the way, could you update your welcome file to show people what combination keys the linebyline has? So far, I only know it supports Ctrl + 1, Ctrl + 2, Ctrl + 3, Ctrl + B, Ctrl + I.

**Comment by halodong** [comment]
The work of supporting HTML has started in part, but it may gradually begin, and not all tags will be supported from the beginning.

Regarding the command section, this module has already started develop. In the next version, a visual table will be added to display the commands and corresponding shortcut keys. In the future, custom shortcut keys will be supported
