### ISSUE TITLE
[BUG]: a bug about refresh

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#191]
**Describe the bug**
When users click the refresh, the linebyline closes md file and path, and then go the Welcome md file.

**To Reproduce**
1. open any md file
2. Click on the bottom part in the editor
3. right click Refresh
4. the linebyline closes all open files and the open path, and then move to the Welcome md file.

**Expected behavior**
just parsing again

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 0.1.0

**Additional context**
I copied/pasted the following into the md file. 
1\.  Bird
1\.  McHale
1\.  Parish

If don't I go dual mode or reopen the md file, they didn't change to
1. Bird 
2. McHale 
3. Parish.

That's why I try to click Refresh. But Refresh seems to work when linebyline can work like a browser, not for the current editor.

**Comment by halodong** [comment]
refer #163
