### ISSUE TITLE
[BUG]: a bug about <u> </u> and <ruby><rt></rt></ruby>

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#260]
**Describe the bug**
when I add a space and a alphabet, the contents of md file can't be shown.

**To Reproduce**
1. open a md file and input the following.
\<u>青春感\</u>
\<ruby>青春感\<rt>せいしゅんかん\</rt>\</ruby>
2. save file. so far it looks ok.
3. open the file and add " a" either in the end of \</u> or \</ruby>
\<u>青春感\</u> a
OR
\<ruby>青春感\<rt>せいしゅんかん\</rt>\</ruby> a
4. Now, you can't see any contents when opening the md file.

**Expected behavior**
show contents

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win 10
 - Version 0.2

**Additional context**

https://drive.google.com/file/d/1q1tUguIgDDxhibwxig15TJ9kOFafeOb0/view?usp=drive_link

**Comment by halodong** [comment]
refer #262
