### ISSUE TITLE
[BUG]: a bug about <mark></mark>

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#261]
**Describe the bug**

0.2 version is great. however, <mark> doesn't work correctly after ">"

**To Reproduce**
1. Open a md file and input  the following
\<mark>青春感\</mark> color is not obvious in the dark theme
\>\<u>青春感\</u>
\>\<ruby>青春感\<rt>せいしゅんかん\</rt>\</ruby>
\>\<mark>青春感\</mark> color is not obvious in the dark theme
2. Then you can see <mark> didn't work correctly after ">"
3. the highlight color isn't obvious in the dark theme.

**Expected behavior**

correctly show the contents
**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.2

**Additional context**

https://drive.google.com/file/d/1q1tUguIgDDxhibwxig15TJ9kOFafeOb0/view?usp=drive_link

**Comment by halodong** [comment]
duplicate #262
