### ISSUE TITLE
[BUG]: a bug - a md file can't be opened.

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#270]
**Describe the bug**
a md file cannot be opened. And then the program give a white screen.

**To Reproduce**
Please check the md file.
https://drive.google.com/file/d/1a2jdXpBDhA3bV6KUco9LuOLs6TYTnbFC/view?usp=sharing

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.2.1

**Additional context**

**Comment by yu2chuan** [comment]
When md files cannot be parsed correctly, the linebyline gives a white screen. It will be a difficult for average users to use it with the other md files which can be parsed. Is it possible to adjust the program behavior and that let users can continue to use it with the other "normal" md files. For example, give a warning such as "this file xxxx can't be parsed" and go back to welcome md file.

**Comment by halodong** [comment]
The version released yesterday included this feature 71559c8.
