### ISSUE TITLE
[BUG]: a bug of adding a file name containing some charactors

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#276]
**Describe the bug**
When adding a file name contains some charactors such as < or >, the program will crash.

**To Reproduce**
1. add file
2. copy and paste a file name including "<"
3. Then, the prgoram will crash.

**Expected behavior**
auto remove those "<" and still add a file name.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.2.2

**Additional context**

**Comment by halodong** [comment]
Will fix this in next version.
