### ISSUE TITLE
[BUG]: a bug of file name note.md

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#277]
**Describe the bug**
After chating with chatGPT and creating a note.md, file name and open folder will not be refreshed.

**To Reproduce**
1. chat in chatGPT and create a note.md
2. press ctrl+s
3. a window pops up, create a new folder, and then save note1234.md.
4. the file name "note.md" and open folder contents will not be refreshed until you re-open this folder.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.2.2

**Additional context**

**Comment by halodong** [comment]
This will be fixed in next version.
