### ISSUE TITLE
[BUG]: a bug of UI

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#279]
**Describe the bug**
Actually, I am not sure whether it is a bug or not. On the version 0.2.2, file name show twice and it occupies extra one row.

**To Reproduce**

If there no specific purpose, 3rd row may not be needed. And move the file name in the 1st row from the right to the middel.
**Screenshots**

**Desktop (please complete the following information):**

 - OS: Win10
 - Version 0.2.2

**Additional context**

**Comment by halodong** [comment]
It was not adapted to windowsOS at that time, and it will be optimized in the next version
