### ISSUE TITLE
[FEATURE]: a feature to "open folder" sorting by folder first and then files.

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#287]
**Is your feature request related to a problem? Please describe.**
Even though folders and files in the open folder are in alphabetical order,  folder and files are mixed together and looks untidy.

**Describe the solution you'd like**

How about folder first and then files. Certainly, they are still in alphabetical order.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by halodong** [comment]
Nice feature, next version will do this.

**Comment by halodong** [comment]
3b61fc53bb83c4a45da10d83de4511e144ab5ba2
