### ISSUE TITLE
[FEATURE]: a feature to support local images

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#289]
**Is your feature request related to a problem? Please describe.**

Generally, ![](local path]image.jpg) can be supported in the markdwon editor.

**Describe the solution you'd like**

local images can be correctly shown on the Linebyline.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by halodong** [comment]
Will specifically improve image-related management later.

**Comment by drl990114** [comment]
c8bd8c36109824639cce13e2dba04acc010d9479
