### ISSUE TITLE
[FEATURE]: a feature about better place for open folder icon

### ISSUE THREAD

**Issue by yu2chuan** [linebyline-group/linebyline#298]
**Is your feature request related to a problem? Please describe.**
Is it possible to optimize the layout to move the open folder icon to the side bar.

**Describe the solution you'd like**

move the open folder icon to the side bar. I believe it will be easier and convenient to choose folder and then search a specific key word.

**Describe alternatives you've considered**

**Additional context**

**Comment by halodong** [comment]
At present, you can use shortcut key `Ctrl + shift + o`  open a folder in windows and linux or `cmd + shift + o` in macos.

About layout, a major upgrade will be made later.
